name: reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of deployable artifact files.
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get codes
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output information
        run: echo "Deploying and Uploading.."